FROM bitnami/minideb:stretch

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    apt-get clean

COPY bin/mqttgateway-x86_64 /mqttgateway
ENTRYPOINT ["/mqttgateway"]
